import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LoginPage from "@/components/LoginForm";
import RegisterForm from "@/components/RegisterForm";
import { AuthProvider } from "./provider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import LoginForm from "@/components/LoginForm";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const RootLayout = async ({ children }) => {
  const session = await getServerSession(authOptions);

  //if (session) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {session ? (
            <div className="flex flex-col bg-base-200 min-h-screen">
              <Navbar />
              <main className="flex-grow bg-base-200 p-4">{children}</main>
              <Footer />
            </div>
          ) : (
            <main className="flex-grow bg-base-200 p-4">{children}</main>
          )}
        </AuthProvider>
      </body>
    </html>
  );
  /*} else {
    return (
      <html lang="en">
        <body>
          <LoginPage 
          {/*<main className="flex-grow bg-base-200 p-4">{children}</main>
        </body>
      </html>
    );*/
};
//};

export default RootLayout;
